### Verbo GET – listar todos
GET http://localhost:8000/cliente/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/cliente/13 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/cliente/ HTTP/1.1
content-type: application/json

{
    "nome" : "Luistest",
    "cpf" : "12345",
    "telefone" : "1000",
    "compra_fiado" : 2,
    "dia_fiado" : 5,
    "senha" : "Luishenrique"
}

### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Paulo",
    "cpf" : "10000000000",
    "telefone" : "937485326458",
    "compra_fiado" : true,
    "dia_fiado" : 5,
    "senha" : "senhaclientetestefiado"
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/cliente/3 HTTP/1.1

