### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/10 HTTP/1.1

### Verbo POST – adicionar
POST http://127.0.0.1:8000/produto/ HTTP/1.1
content-type: application/json

{
    "nome" : "Pastel1",
    "descricao" : "carne",
    "foto" : "foto12",
    "valor_unit" : 12
}


### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Pastel",
    "descricao" : "queijo",
    "foto" : "foto",
    "valor_unit" : 15
}

### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/produto/2 HTTP/1.1

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
### Verbo GET – listar todos
curl -X 'GET' \
'http://localhost:8000/funcionario/' \
-H 'accept: application/json' \
-H 'x-token: abcBolinhasToken' \
-H 'x-key: abcBolinhasKey'